dist: trusty
sudo: required
language: python
python:
    - "3.5"

install: 
    - sudo apt-get install python-dbus
    - pip install -r requirements.txt

script:
    - make clean
    - make check
    - make test
    - make coverage
